# Generated by Django 5.2.16 on 2026-07-18 04:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO标题')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO关键词')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO描述')),
                ('category', models.CharField(default='行业资讯', max_length=50, verbose_name='文章分类')),
                ('cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('author', models.CharField(default='管理员', max_length=50, verbose_name='作者')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('status', models.IntegerField(choices=[(1, '已发布'), (0, '已下架')], default=1, verbose_name='状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
                ('ext_field2', models.TextField(blank=True, null=True, verbose_name='扩展字段2')),
            ],
            options={
                'verbose_name': '资讯文章',
                'verbose_name_plural': '资讯文章',
                'db_table': 'article',
                'ordering': ['-is_top', '-sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='留言内容')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源页面')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='精简答案（2-3句）')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详细展开说明')),
                ('category', models.CharField(default='通用', max_length=50, verbose_name='分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
            ],
            options={
                'verbose_name': 'FAQ问答',
                'verbose_name_plural': 'FAQ问答',
                'db_table': 'faq',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LABOR-SAVING 气动助力机械臂', max_length=100, verbose_name='站点名称')),
                ('site_title', models.CharField(default='气动助力机械臂厂家 | 工业机械臂解决方案', max_length=200, verbose_name='站点标题')),
                ('site_keywords', models.CharField(default='气动助力机械臂,助力臂,机械臂厂家,工业自动化', max_length=255, verbose_name='站点关键词')),
                ('site_description', models.TextField(default='LABOR-SAVING 专注气动助力机械臂研发生产，提供工业自动化助力解决方案。', verbose_name='站点描述')),
                ('company_name', models.CharField(default='LABOR-SAVING 智能装备有限公司', max_length=100, verbose_name='企业名称')),
                ('company_intro', models.TextField(blank=True, null=True, verbose_name='企业简介')),
                ('founded_year', models.IntegerField(default=2015, verbose_name='成立年份')),
                ('company_scale', models.CharField(blank=True, max_length=100, null=True, verbose_name='经营规模')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='资质实力')),
                ('office_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='办公地址')),
                ('service_scope', models.TextField(blank=True, null=True, verbose_name='服务范围')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('contact_qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系QQ')),
                ('baidu_verify', models.CharField(blank=True, max_length=100, null=True, verbose_name='百度验证代码')),
                ('baidu_tongji', models.CharField(blank=True, max_length=50, null=True, verbose_name='百度统计ID')),
                ('baidu_push_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='百度推送Token')),
                ('qihu_verify', models.CharField(blank=True, max_length=100, null=True, verbose_name='360验证代码')),
                ('sogou_verify', models.CharField(blank=True, max_length=100, null=True, verbose_name='搜狗验证代码')),
                ('google_verify', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google验证代码')),
                ('google_ga_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Analytics ID')),
                ('google_ads_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Ads ID')),
                ('gtm_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='GTM容器ID')),
                ('ext_config1', models.TextField(blank=True, null=True, verbose_name='扩展配置1')),
                ('ext_config2', models.TextField(blank=True, null=True, verbose_name='扩展配置2')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
                'db_table': 'site_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
                ('ext_field2', models.TextField(blank=True, null=True, verbose_name='扩展字段2')),
                ('groups', models.ManyToManyField(blank=True, related_name='api_users', to='auth.group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='api_users', to='auth.permission', verbose_name='用户权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
