# Generated by Django 5.2.16 on 2026-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('icon', models.CharField(default='🔧', max_length=10, verbose_name='显示图标')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('category', models.CharField(default='核心产品', max_length=50, verbose_name='产品分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'product',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
