# Generated by Django 5.2.16 on 2026-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_siteconfig_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='qihu_push_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='360自动收录脚本URL'),
        ),
    ]
