# Generated by Django 5.2.16 on 2026-07-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_siteconfig_qihu_push_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('key_prefix', models.CharField(max_length=12, verbose_name='密钥前缀')),
                ('key_hash', models.CharField(max_length=128, verbose_name='密钥哈希')),
                ('scopes', models.CharField(choices=[('read', '只读'), ('write', '读写'), ('admin', '管理')], default='read', max_length=20, verbose_name='权限范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥管理',
                'db_table': 'api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP地址/CIDR')),
                ('rule_type', models.CharField(choices=[('allow', '白名单'), ('deny', '黑名单')], default='deny', max_length=10, verbose_name='规则类型')),
                ('scope', models.CharField(choices=[('all', '全站'), ('admin', '后台管理'), ('api', 'API接口')], default='all', max_length=10, verbose_name='生效范围')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'IP规则',
                'verbose_name_plural': 'IP黑白名单',
                'db_table': 'ip_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件标题')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='文件')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频')], default='image', max_length=20, verbose_name='媒体类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME类型')),
                ('uploaded_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='上传者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ext_field1', models.CharField(blank=True, max_length=100, null=True, verbose_name='扩展字段1')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体图库',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图URL'),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('action', models.CharField(choices=[('login', '登录成功'), ('logout', '退出登录'), ('failed', '登录失败')], max_length=20, verbose_name='动作')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='api.media', verbose_name='封面图(媒体库)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='api.media', verbose_name='证书图片(媒体库)'),
        ),
    ]
