# Generated by Django 5.2.16 on 2026-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apikey_iprule_media_article_slug_alter_article_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='icp_beian',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ICP备案号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='icp_link',
            field=models.CharField(blank=True, default='https://beian.miit.gov.cn', max_length=200, null=True, verbose_name='备案查询链接'),
        ),
    ]
