# Generated by Django 5.2.16 on 2026-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_siteconfig_icp_beian_siteconfig_icp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='投资预算区间'),
        ),
        migrations.AddField(
            model_name='contact',
            name='intent_region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='意向代理区域'),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='线索来源(ai/search/direct/other)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='same_as',
            field=models.TextField(blank=True, null=True, verbose_name='权威外链sameAs'),
        ),
    ]
